import { IButtonComponentConfig, IColumnConfig, IDividerComponentConfig, IHTMLComponentConfig, IImageComponentConfig, IMenuComponentConfig, IRowConfig, ISocialComponentConfig, ITextComponentConfig } from "../interfaces/mainInterface";

export const ROW_CONFIG: IRowConfig = {
  paddingTop: 5,
  paddingBottom: 5,
  paddingLeft: 5,
  paddingRight: 5,
  backgroundColor: "white",
  backgroundImage: null,
  height: 10,
  content: "content",
  vAlign: "top",
  borderWidth: 5,
  borderColor: "#00000000",
  borderTopLeft: false,
  borderTopRight: false,
  borderBottomLeft: false,
  borderBottomRight: false,
  borderTop: false,
  borderRight: false,
  borderLeft: false,
  borderBottom: false
}

export const COLUMN_CONFIG: IColumnConfig = {
  applyBg: false,
  paddingTop: 0,
  paddingBottom: 0,
  paddingLeft: 0,
  paddingRight: 0,
  backgroundColor: "#00000000",
  backgroundImage: null,
  borderWidth: 0,
  borderColor: "#00000000",
  borderRadius: 0,
  align: "col",
  maxWidth: 100,
  borderTopLeft: false,
  borderTopRight: false,
  borderBottomLeft: false,
  borderBottomRight: false,
  borderTop: false,
  borderRight: false,
  borderLeft: false,
  borderBottom: false,
  spacing: 16,
}

export const TEXT_COMPONENT_CONFIG: ITextComponentConfig = {
  textSize: 16,
  textColor: "rgba(0,0,0,1)",
  width: 100,
  height: "auto",
  minHeight: 190,
  maxHeight: 300,
  bgColor: "rgba(0,0,0,0)",
  align: "left",
  borderRadius: 0,
  paddingTop: 8,
  paddingBottom: 8,
  paddingLeft: 5,
  paddingRight: 5,
  fieldPaddingTop: 0,
  fieldPaddingBottom: 0,
  fieldPaddingLeft: 0,
  fieldPaddingRight: 0,
  fontWeight: 400,
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  objectFit: "cover",
  borderColor: "rgba(0,0,0,0)",
  borderWidth: 0,
  dividerType: "solid",
  dividerColor: "black",
  showFieldLabelSettingIconId: null,
  showFieldLabel: false,
  showAdditionalFields: false,
  fieldTextAlignment: "row",
  buttonColor: "rgb(56, 98, 206)",
  imageRadius: 0,
  imageBackground: "rgba(0,0,0,0)",
  letterSpacing: 0
}

export const IMAGE_COMPONENT_CONFIG: IImageComponentConfig = {
  textSize: 16,
  textColor: "black",
  width: 680,
  height: "auto",
  minHeight: 190,
  maxHeight: 250,
  bgColor: "rgba(0,0,0,0)",
  align: "left",
  borderRadius: 0,
  paddingTop: 8,
  paddingBottom: 8,
  paddingLeft: 5,
  paddingRight: 5,
  fieldPaddingTop: 0,
  fieldPaddingBottom: 0,
  fieldPaddingLeft: 0,
  fieldPaddingRight: 0,
  fontWeight: 400,
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  objectFit: "cover",
  borderColor: "rgba(0,0,0,0)",
  borderWidth: 1,
  dividerType: "solid",
  dividerColor: "black",
  showFieldLabelSettingIconId: null,
  showFieldLabel: false,
  showAdditionalFields: false,
  fieldTextAlignment: "row",
  buttonColor: "rgb(56, 98, 206)",
  imageRadius: 0,
  imageBackground: "rgba(0,0,0,0)",
  letterSpacing: 0,
  borderTopLeft: true,
  borderTopRight: true,
  borderBottomLeft: true,
  borderBottomRight: false
}

export const BUTTON_COMPONENT_CONFIG: IButtonComponentConfig = {
  textSize: 16,
  textColor: "rgb(0, 0, 0)",
  width: 120,
  height: "auto",
  minHeight: 190,
  maxHeight: 300,
  bgColor: "rgba(0,0,0,0)",
  align: "start",
  borderRadius: 0,
  paddingTop: 8,
  paddingBottom: 8,
  paddingLeft: 5,
  paddingRight: 5,
  fieldPaddingTop: 6,
  fieldPaddingBottom: 6,
  fieldPaddingLeft: 0,
  fieldPaddingRight: 0,
  fontWeight: 400,
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  objectFit: "cover",
  borderColor: "rgb(0, 0, 0)",
  borderWidth: 1,
  dividerType: "solid",
  dividerColor: "black",
  showFieldLabelSettingIconId: null,
  showFieldLabel: false,
  showAdditionalFields: false,
  fieldTextAlignment: "row",
  buttonColor: "rgb(255, 255, 255)",
  imageRadius: 0,
  imageBackground: "rgba(0,0,0,0)",
  letterSpacing: 0
}

export const DIVIDER_COMPONENT_CONFIG: IDividerComponentConfig = {
  textSize: 16,
  textColor: "black",
  width: 100,
  widthValueIn: "%",
  height: 3,
  minHeight: 190,
  maxHeight: 300,
  bgColor: "rgba(0,0,0,0)",
  align: "left",
  borderRadius: 0,
  paddingTop: 8,
  paddingBottom: 8,
  paddingLeft: 5,
  paddingRight: 5,
  fieldPaddingTop: 0,
  fieldPaddingBottom: 0,
  fieldPaddingLeft: 0,
  fieldPaddingRight: 0,
  fontWeight: 400,
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  objectFit: "cover",
  borderColor: "rgba(0,0,0,0)",
  borderWidth: 0,
  dividerType: "solid",
  dividerColor: "black",
  showFieldLabelSettingIconId: null,
  showFieldLabel: false,
  showAdditionalFields: false,
  fieldTextAlignment: "row",
  buttonColor: "rgb(56, 98, 206)",
  imageRadius: 0,
  imageBackground: "rgba(0,0,0,0)",
  letterSpacing: 0
}

export const SOCIAL_COMPONENT_CONFIG: ISocialComponentConfig = {
  textSize: 16,
  textColor: "black",
  width: 50,
  height: 50,
  minHeight: 190,
  maxHeight: 300,
  bgColor: "rgba(0,0,0,0)",
  align: "left",
  borderRadius: 0,
  paddingTop: 8,
  paddingBottom: 8,
  paddingLeft: 5,
  paddingRight: 5,
  fieldPaddingTop: 0,
  fieldPaddingBottom: 0,
  fieldPaddingLeft: 0,
  fieldPaddingRight: 0,
  fontWeight: 400,
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  objectFit: "cover",
  borderColor: "rgba(0,0,0,0)",
  borderWidth: 0,
  dividerType: "solid",
  dividerColor: "black",
  showFieldLabelSettingIconId: null,
  showFieldLabel: false,
  showAdditionalFields: false,
  fieldTextAlignment: "row",
  buttonColor: "rgb(56, 98, 206)",
  imageRadius: 0,
  imageBackground: "rgba(0,0,0,0)",
  letterSpacing: 0
}

export const MENU_COMPONENT_CONFIG: IMenuComponentConfig = {
  activeLinkIndex: 0,
  activeLinkColor: "red",
  activeLinkName: "Home",
  textSize: 16,
  textColor: "black",
  width: 100,
  height: "auto",
  minHeight: 190,
  maxHeight: 300,
  bgColor: "rgba(0,0,0,0)",
  align: "right",
  borderRadius: 0,
  paddingTop: 5,
  paddingBottom: 5,
  paddingLeft: 8,
  paddingRight: 8,
  fieldPaddingTop: 0,
  fieldPaddingBottom: 0,
  fieldPaddingLeft: 0,
  fieldPaddingRight: 0,
  fontWeight: 400,
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  objectFit: "cover",
  borderColor: "rgba(0,0,0,0)",
  borderWidth: 0,
  dividerType: "solid",
  dividerColor: "black",
  showFieldLabelSettingIconId: null,
  showFieldLabel: false,
  showAdditionalFields: false,
  fieldTextAlignment: "row",
  buttonColor: "rgb(56, 98, 206)",
  imageRadius: 0,
  imageBackground: "rgba(0,0,0,0)",
  letterSpacing: 0
}

export const HTML_COMPONENT_CONFIG: IHTMLComponentConfig = {
  html_content: "<p>Customize your HTML code here</p>"
}